import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer',
  description: 'Disclaimer for Life Path Numerology Calculator. Please read before using this site.',
  alternates: { canonical: 'https://yournumerologyreport.com/disclaimer' },
  robots: { index: false, follow: false },
};

const LAST_UPDATED = '1 April 2025';

const sections = [
  {
    id: 'general',
    heading: 'General information only',
    body: `The content published on Life Path Numerology Calculator — including all life path number descriptions, personal year calculations, and any other numerological content — is provided for informational and self-reflection purposes only. It does not constitute professional advice of any kind, including but not limited to psychological, medical, financial, legal, or therapeutic advice.

Numerology is a symbolic interpretive framework, not an empirical science. The results generated by this calculator are based on traditional numerological methods and are intended to prompt reflection, not to predict outcomes or define identity. You should not make significant life decisions based solely on the results of any numerological reading.`,
  },
  {
    id: 'accuracy',
    heading: 'No guarantee of accuracy',
    body: `While we take care to ensure that the calculation methods and number descriptions on this site are consistent with recognised numerological traditions, we make no representations or warranties — express or implied — regarding the accuracy, completeness, or suitability of the information provided.

Numerological interpretations vary across traditions, schools, and practitioners. The meanings and descriptions on this site reflect one coherent framework and should not be taken as universally agreed upon or scientifically validated.`,
  },
  {
    id: 'personal-responsibility',
    heading: 'Personal responsibility',
    body: `Any action you take based on the content of this website is strictly at your own discretion and risk. Life Path Numerology Calculator accepts no responsibility for how you interpret or act upon any result, reading, or description provided on this site.

If you are experiencing difficulties related to mental health, relationships, finances, or any other significant life area, we strongly encourage you to seek qualified professional support. This site is not a substitute for that.`,
  },
  {
    id: 'liability',
    heading: 'Limitation of liability',
    body: `To the fullest extent permitted by applicable law, Life Path Numerology Calculator, its operators, contributors, and affiliates shall not be held liable for any direct, indirect, incidental, consequential, or special damages arising from your use of — or inability to use — this website or its content.

This includes, without limitation, any loss of data, loss of profit, or any other loss arising from reliance on information published on this site.`,
  },
  {
    id: 'entertainment',
    heading: 'Entertainment and self-reflection',
    body: `Life Path Numerology Calculator is designed as an intelligent tool for self-reflection. The framework we use is drawn from classical Pythagorean numerology, as documented and expanded by practitioners including Dan Millman and Matthew Oliver Goodwin. We present this tradition with clarity and without exaggerated claims.

If you find value in numerology as a lens through which to understand your patterns, tendencies, and purpose — that is the intended use of this site. It is not intended to be taken literally as prophecy or fixed fate.`,
  },
  {
    id: 'external-links',
    heading: 'External links',
    body: `This website may in the future contain links to third-party websites for reference or additional reading. These links are provided for convenience only. Life Path Numerology Calculator has no control over the content of external sites and accepts no responsibility for their accuracy, legality, or any other aspect of their content or privacy practices.

The inclusion of any link does not constitute an endorsement of that site or its operators.`,
  },
  {
    id: 'intellectual-property',
    heading: 'Intellectual property',
    body: `All original text, design, code, and content on Life Path Numerology Calculator is the property of Life Path Numerology Calculator and is protected under applicable copyright law. You may not reproduce, distribute, or republish any part of this site without prior written permission.

The underlying calculation method (summing all digits of the date of birth and reducing to a single digit or Master Number) is a traditional technique in the public domain. The specific descriptions, prose, and presentation on this site are original work.`,
  },
  {
    id: 'changes',
    heading: 'Changes to this disclaimer',
    body: `We reserve the right to update or modify this disclaimer at any time without prior notice. Changes will be reflected on this page with an updated date. Continued use of this site following any changes constitutes your acceptance of the revised disclaimer.

We recommend checking this page periodically if you use this site regularly.`,
  },
  {
    id: 'contact',
    heading: 'Contact',
    body: `If you have any questions about this disclaimer or the content on this site, you are welcome to contact us via the details listed on our Privacy Policy page. We will do our best to respond in a timely manner.`,
  },
];

export default function DisclaimerPage() {
  return (
    <main className="pt-24">
      {/* Header */}
      <section className="border-b border-white/5 px-6 py-20">
        <div className="mx-auto max-w-3xl">
          <p className="mb-4 font-body text-xs uppercase tracking-[0.2em] text-[#c9a84c]/70">
            Legal
          </p>
          <h1 className="mb-4 font-display text-[clamp(2rem,5vw,3.5rem)] font-light leading-tight text-[#f0ede8]">
            Disclaimer
          </h1>
          <p className="font-body text-sm text-[#f0ede8]/35">
            Last updated: {LAST_UPDATED}
          </p>
        </div>
      </section>

      {/* Intro */}
      <section className="border-b border-white/5 px-6 py-12">
        <div className="mx-auto max-w-3xl">
          <p className="font-body text-base leading-relaxed text-[#f0ede8]/65">
            By using Life Path Numerology Calculator you agree to the terms set out in this disclaimer. Please
            read it carefully before using any content or results provided on this site. If you do
            not agree with any part of this disclaimer, please do not use this website.
          </p>
        </div>
      </section>

      {/* Sections */}
      <div className="px-6 py-12">
        <div className="mx-auto max-w-3xl space-y-12">
          {sections.map(({ id, heading, body }) => (
            <section key={id} id={id} className="scroll-mt-28 border-t border-white/5 pt-10">
              <h2 className="mb-5 font-display text-2xl font-light text-[#f0ede8]">{heading}</h2>
              <div className="space-y-4">
                {body.split('\n\n').map((para, i) => (
                  <p key={i} className="font-body text-base leading-relaxed text-[#f0ede8]/65">
                    {para}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>
      </div>
    </main>
  );
}
